# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prngmgr', '0008_auto_20161010_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peeringrouterixinterface',
            name='netixlan',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prngrtriface_set', to='django_peeringdb.NetworkIXLan'),
        ),
        migrations.AlterField(
            model_name='peeringsession',
            name='peer_netixlan',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prngsess_set', to='django_peeringdb.NetworkIXLan'),
        ),
    ]
